redis:
  image: redis:latest
  ports:
    - "6379:6379"

backend:
  build:
    context: ./backend
    dockerfile: Dockerfile
  ports:
    - "8000:8000"

postgres:
  image: postgres:15
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
  volumes:
    - postgres_data:/var/lib/postgresql/data